sudo: false
language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.3.1"

cache:
  pip: true
  directories:
    - $HOME/.ccache

env:
  global:
      - PATH="/usr/lib/ccache:$PATH"

install:
  - "pip install -U pip 'setuptools!=26.*'"
  - "pip install ."
  - "pip install -r test_requirements.txt"
  - "pip install flake8"
before_script: "flake8 --max-complexity 10 src/brotli test"
script:
  - >
      if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then
        py.test -n 2 test/
      else
        py.test -n 2 --cov brotli test/
      fi
