name: Wheels
on: [push, pull_request]

jobs:
  wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - name: manylinux
          os: ubuntu-latest
        - name: macos
          os: macos-latest
        - name: win
          os: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: choco install vcpython27 -f -y
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp27-${{ matrix.name }}* cp35-${{ matrix.name }}* pp*-${{ matrix.name }}*
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
